TARGET = babakjan

CXX = g++
CXX_FLAGS = -Wall -pedantic -Wextra -std=c++14

MKDIR = mkdir -p
BUILD_DIR = build

.PHONY: all
all: compile

.PHONY: compile
compile: $(TARGET)

.PHONY: run
run: $(TARGET)
	./$(TARGET)

$(TARGET): $(BUILD_DIR)/main.o $(BUILD_DIR)/CApplication.o $(BUILD_DIR)/CBonusLongerPaddle.o $(BUILD_DIR)/CBonusSlowTimeLongerPaddle.o $(BUILD_DIR)/CBonusSlowTime.o $(BUILD_DIR)/CBufferSwitch.o $(BUILD_DIR)/CMenu.o $(BUILD_DIR)/CPlayingBoard.o  $(BUILD_DIR)/TBall.o $(BUILD_DIR)/TPaddle.o
	$(CXX) $(CXX_FLAGS) $^ -o $@

$(BUILD_DIR)/%.o: src/%.cpp
	$(MKDIR) $(BUILD_DIR)
	$(CXX) $(CXX_FLAGS) $< -c -o $@

.PHONY: clean
clean:
	rm -rf $(TARGET) $(BUILD_DIR)/ 2>/dev/null

doc: src/CApplication.h src/CBonus.h src/CBonusLongerPaddle.h src/CBonusNothing.h src/CBonusSlowTime.h src/CBonusSlowTimeLongerPaddle.h src/CBufferSwitch.h src/CMenu.h src/Colors.h src/CPlayingBoard.h src/EDirection.h src/EReturnVal.h src/TBall.h src/TPaddle.h src/TKeyboardDetector.h
	doxygen Doxyfile

#depencencies (generated by "g++ -MM src/*.cpp")
$(BUILD_DIR)CApplication.o: src/CApplication.cpp src/CApplication.h \
 src/CPlayingBoard.h src/TBall.h src/EDirection.h src/TPaddle.h \
 src/CBonus.h src/Colors.h src/CBonusNothing.h src/CBonusSlowTime.h \
 src/CBonusLongerPaddle.h src/CBonusSlowTimeLongerPaddle.h \
 src/EReturnVal.h src/CBufferSwitch.h src/CMenu.h src/TKeyboardDetector.h
$(BUILD_DIR)CBonusLongerPaddle.o: src/CBonusLongerPaddle.cpp src/CBonusLongerPaddle.h \
 src/CBonus.h src/TPaddle.h src/Colors.h
$(BUILD_DIR)CBonusSlowTime.o: src/CBonusSlowTime.cpp src/CBonusSlowTime.h \
 src/CBonus.h src/TPaddle.h src/Colors.h
$(BUILD_DIR)CBonusSlowTimeLongerPaddle.o: src/CBonusSlowTimeLongerPaddle.cpp \
 src/CBonusSlowTimeLongerPaddle.h src/CBonus.h src/TPaddle.h src/Colors.h
$(BUILD_DIR)CBufferSwitch.o: src/CBufferSwitch.cpp src/CBufferSwitch.h
$(BUILD_DIR)CMenu.o: src/CMenu.cpp src/CMenu.h src/CPlayingBoard.h src/TBall.h \
 src/EDirection.h src/TPaddle.h src/CBonus.h src/Colors.h \
 src/CBonusNothing.h src/CBonusSlowTime.h src/CBonusLongerPaddle.h \
 src/CBonusSlowTimeLongerPaddle.h src/EReturnVal.h src/CBufferSwitch.h \
 src/TKeyboardDetector.h
$(BUILD_DIR)CPlayingBoard.o: src/CPlayingBoard.cpp src/CPlayingBoard.h src/TBall.h \
 src/EDirection.h src/TPaddle.h src/CBonus.h src/Colors.h \
 src/CBonusNothing.h src/CBonusSlowTime.h src/CBonusLongerPaddle.h \
 src/CBonusSlowTimeLongerPaddle.h src/EReturnVal.h
$(BUILD_DIR)main.o: src/main.cpp src/CApplication.h src/CPlayingBoard.h src/TBall.h \
 src/EDirection.h src/TPaddle.h src/CBonus.h src/Colors.h \
 src/CBonusNothing.h src/CBonusSlowTime.h src/CBonusLongerPaddle.h \
 src/CBonusSlowTimeLongerPaddle.h src/EReturnVal.h src/CBufferSwitch.h \
 src/CMenu.h src/TKeyboardDetector.h
$(BUILD_DIR)TBall.o: src/TBall.cpp src/TBall.h src/EDirection.h
$(BUILD_DIR)TPaddle.o: src/TPaddle.cpp src/TPaddle.h

#inspired by PA2 stream https://youtu.be/qmgZF5ijax8

